---
# tasks file for app-janni

- name: Check for installation of Anaconda
  become: yes
  stat:
    path: '{{ janni_install_dir }}/bin/conda'
  changed_when: false
  register: anaconda_conda_binary

- when: not anaconda_conda_binary.stat.exists
  block:
    - name: Download Anaconda installer.
      become: yes
      get_url:
        url: '{{anaconda_installer_url}}'
        dest: /tmp/{{anaconda_installer_sh}}
        timeout: '{{anaconda_timeout_seconds}}'
        checksum: '{{anaconda_checksum}}'
        mode: 0755

    - name: Run Anaconda installer.
      become: yes
      command: bash /tmp/{{anaconda_installer_sh}} -b -f -p {{janni_install_dir}}

  always:
    - name: Delete Anaconda installer.
      become: yes
      file:
        path: /tmp/{{anaconda_installer_sh}}
        state: absent

- name: Add conda base environment file.
  become: yes
  copy:
    content: '{{ anaconda_base_env | to_nice_yaml }}'
    dest: /tmp/anaconda-base.yml
  when: anaconda_base_env is defined and not anaconda_conda_binary.stat.exists

- name: Install additional packages to universal install / add default packages to shared package cache.
  become: yes
  shell: |
    source {{janni_install_dir}}/bin/activate
    conda env update -f=/tmp/anaconda-base.yml
  when: anaconda_base_env is defined and not anaconda_conda_binary.stat.exists

# imagecodecs-lite consistently fails since its setup scripts depend upong
# Cython and Numpy being installed before it will work with a pip install
- name: Workaround for imagecodecs-lite dependency hell issue
  become: yes
  shell: |
    source {{janni_install_dir}}/bin/activate
    pip install numpy==1.14.5
    pip install cython==0.29.21
    pip install {% for dep in janni_pip_dependencies %}{{ dep }} {% endfor %}
  when: janni_pip_dependencies is defined and anaconda_base_env is defined and not anaconda_conda_binary.stat.exists

- name: Remove conda base environment file.
  become: yes
  file:
    path: /tmp/anaconda-base.yml
    state: absent
  when: anaconda_base_env is defined and not anaconda_conda_binary.stat.exists

- name: Add in function to unload conda module
  copy:
    src: deinit-bash.sh
    dest: "{{ janni_install_dir }}/bin/deinit-bash.sh"
  when: janni_module 
- name: Add in janni module
  template:
    src: janni.lua.j2
    dest: "{{ janni_module_dir }}/janni.lua"
  when: janni_module and janni_module_dir is defined
